import { describe, expect, it } from "vitest";

import * as identitySecurity from "../src/index.js";

describe("identity security public API", () => {
  it("exports the complete supported runtime surface", () => {
    expect(Object.keys(identitySecurity).sort()).toEqual(
      [
        "BrowserRequestPolicy",
        "ConfiguredDummyPasswordHash",
        "DeliverySecretEnvelopeService",
        "DEFAULT_DELIVERY_ENVELOPE_TTL_SECONDS",
        "DELIVERY_SECRET_ENVELOPE_AUTH_TAG_BYTES",
        "DELIVERY_SECRET_ENVELOPE_KEY_BYTES",
        "DELIVERY_SECRET_ENVELOPE_NONCE_BYTES",
        "DELIVERY_SECRET_ENVELOPE_VERSION",
        "IdentityDeliverySecretEnvelopeAdapter",
        "IdentityRecoveryCodeServiceAdapter",
        "IdentitySecurityConfigurationError",
        "IdentityTokenServiceRegistry",
        "IdentityTotpSecretCipherAdapter",
        "InstallationTotpService",
        "InvalidDeliverySecretEnvelopeError",
        "MAXIMUM_AUDIT_INTEGRITY_KEY_BYTES",
        "MAX_DELIVERY_SECRET_BYTES",
        "MINIMUM_AUDIT_INTEGRITY_KEY_BYTES",
        "NodeUuidGenerator",
        "createIdentitySecurityAdapters",
        "isSupportedPasswordHash",
        "loadIdentitySecurityConfiguration",
        "CSRF_COOKIE",
        "CSRF_HEADER_NAME",
        "CsrfTokenService",
        "HmacIdentityAuditIntegrity",
        "InvalidEncryptedTotpSecretError",
        "InvalidPasswordHashError",
        "MAX_PASSWORD_BYTES",
        "NodeCryptoArgon2idDeriver",
        "NodeRandomSource",
        "OpaqueTokenService",
        "PASSWORD_HASH_POLICY",
        "PERSISTED_TOKEN_HASH_BYTES",
        "PRE_AUTH_CSRF_BINDING",
        "PasswordHashingService",
        "RECOVERY_CODE_COUNT",
        "RECOVERY_CODE_RANDOM_BYTES",
        "RecoveryCodeService",
        "SESSION_COOKIE",
        "SESSION_TOKEN_DOMAIN",
        "SessionTokenService",
        "SystemClock",
        "TOTP_POLICY",
        "TOTP_SECRET_ENCRYPTION_AUTH_TAG_BYTES",
        "TOTP_SECRET_ENCRYPTION_KEY_BYTES",
        "TOTP_SECRET_ENCRYPTION_NONCE_BYTES",
        "TOTP_SECRET_ENCRYPTION_VERSION",
        "TotpSecretEncryptionService",
        "TotpService",
        "constantTimeEqual",
        "createPersistedTokenHash",
        "createTotpProvisioningUri",
        "generateHotp",
        "normalizeRecoveryCode",
        "persistedTokenHashBytes",
      ].sort(),
    );
  });
});
