export {
  LocationDirectory,
  hierarchyNodeKinds,
  operationalLocationKinds,
  type AddHierarchyNode,
  type CreateBranch,
  type HierarchyLocationNode,
  type HierarchyNodeKind,
  type HierarchyOperationalKind,
  type LocationDirectorySnapshot,
  type LocationRetirementFacts,
  type LocationRetirementOutcome,
  type OperationalLocationKind,
  type PhysicalLocationStatus,
} from "./locations/directory.js";
export { LocationDomainError, type LocationDomainErrorCode } from "./locations/errors.js";
export {
  copyGeometry,
  createPolygonGeometry,
  createRectangleGeometry,
  type MapGeometry,
  type NormalizedPoint,
  type PolygonGeometry,
  type RectangleGeometry,
} from "./locations/geometry.js";
export {
  BuildingMap,
  mapRegionStatusPresentation,
  type AddMapRegion,
  type BlankMapBackground,
  type BuildingMapSnapshot,
  type DerivedStockStatus,
  type FloorPlanMapBackground,
  type MapBackground,
  type MapRegion,
  type MapRegionStatus,
  type MapRegionStatusPresentation,
  type MapStatus,
  type UpdateMapRegion,
} from "./locations/map.js";
export {
  createDocumentId,
  createLocationCode,
  createLocationId,
  createLocationName,
  createMapId,
  createMapRegionId,
  type DocumentId,
  type LocationCode,
  type LocationId,
  type LocationName,
  type MapId,
  type MapRegionId,
} from "./locations/value-objects.js";
