"""Initial migration

Revision ID: b7d55dd33863
Revises: 
Create Date: 2025-11-22 19:48:26.587930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7d55dd33863'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # This is an initial empty migration that sets up the alembic_version table.
    # Database models will be added in subsequent migrations.
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # This is an initial empty migration that sets up the alembic_version table.
    # Database models will be added in subsequent migrations.
    pass
    # ### end Alembic commands ###
