export const API_TOKENS = {
  authenticationGuard: Symbol("auth.guard"),
  catalogueService: Symbol("inventory.catalogue-service"),
  dashboardService: Symbol("dashboard.service"),
  jobsService: Symbol("jobs.service"),
  issuesService: Symbol("issues.service"),
  signInRateLimiter: Symbol("auth.sign-in-rate-limiter"),
  sessionService: Symbol("auth.session-service"),
  stockRequestsService: Symbol("requests.stock-requests-service"),
  stockService: Symbol("inventory.stock-service"),
  usersService: Symbol("users.service"),
  locationsService: Symbol("locations.service"),
  photosService: Symbol("photos.service"),
  publicAppOrigin: Symbol("auth.public-app-origin"),
  expiredSessionSweeper: Symbol("auth.expired-session-sweeper"),
  stockCaptureConfiguration: Symbol("stock-capture.configuration"),
  stockCaptureService: Symbol("stock-capture.service"),
  mcpConfiguration: Symbol("mcp.configuration"),
  mcpAuditService: Symbol("mcp.audit-service"),
  mcpOAuthService: Symbol("mcp.oauth-service"),
  mcpToolExecutor: Symbol("mcp.tool-executor"),
  mcpActivityService: Symbol("mcp.activity-service"),
  mcpReconciliationJob: Symbol("mcp.reconciliation-job"),
  mcpRateLimiter: Symbol("mcp.rate-limiter"),
} as const;
